Repository cryptape/cyton-ios, pull requests merged in 2018-11, with the labels that each got.

#112 Simplify wallet manager result
  Neuron.xcodeproj/project.pbxproj
  Neuron/Sections/Wallet/TokensViewController.swift
  Neuron/Sections/Wallet/View/ChangePasswordController.swift
  Neuron/Sections/Wallet/View/VerifyMnemonicViewController.swift
  Neuron/Sections/Wallet/View/WalletDetailController.swift
  Neuron/Sections/Wallet/ViewModel/ImportWalletViewModel.swift
  Neuron/Service/DAppService/ETHSignMessageService.swift
  Neuron/Service/SensorsAnalytics/SensorsAnalytics.swift
  Neuron/Service/TokenServices/NervosTransactionService.swift
  Neuron/Service/WalletManager/WalletKeystoreManager.swift
  Neuron/Service/WalletManager/WalletManager+Errors.swift
  Neuron/Service/WalletManager/WalletManager.swift
  Neuron/Service/WalletTools/ExportError.swift
  Neuron/Service/WalletTools/ExportResult.swift
  Neuron/Service/WalletTools/ImportError.swift
  Neuron/Service/WalletTools/ImportResult.swift
  Neuron/Service/WalletTools/ImportType.swift
  Neuron/Service/WalletTools/KeystoreError.swift
  Neuron/Service/WalletTools/WalletManager.swift
  Neuron/en.lproj/Localizable.strings
  Neuron/zh-Hans.lproj/Localizable.strings
  NeuronTests/Service/WalletManager/WalletManagerTests.swift
  Podfile
  Podfile.lock
Labels: refactoring

#137 Fix navigation controller translucent
  Neuron.xcodeproj/project.pbxproj
  Neuron/Sections/Wallet/View/GenerateMnemonicController.swift
  Neuron/Sections/Wallet/View/GenerateMnemonicController.xib
Labels: bug

#174 Move UIKit protocols/helpers to Utils, delete ShareItem class
  Neuron.xcodeproj/project.pbxproj
  Neuron/Utils/ShareItem.swift
  Neuron/Utils/UIKit/FixSwipeBackable.swift
  Neuron/Utils/UIKit/NoScreenshot.swift
  Neuron/Utils/UIKit/Overlay.storyboard
  Neuron/Utils/UIKit/OverlayPresentable.swift
  Neuron/Utils/UIKit/Toast.swift
  Neuron/Utils/UIKit/ToastActivityView.xib
Labels: enhancement

#184 Fix keystore format
  Neuron/Sections/Wallet/WalletDetails/WalletDetailController.swift
  Neuron/Services/WalletManager/WalletManager.swift
Labels: enhancement
